### ISSUE TITLE
v0.4.24 returns "Error occurred, contact support"

### ISSUE THREAD

**Issue by twmills** [gemfury/gemfury#20]
When we `rake release` on v0.4.24 we get the "contact support" error, but not when we roll back to v0.4.23.

Is there something we need to configure on our account for v0.4.24?

**Comment by rykov** [comment]
Are you still seeing this error in v0.4.26 or the latest v0.5.0 prerelease?

**Comment by rykov** [comment]
@twmills Is this still an issue?  Please upgrade to v0.6.0 and try this again.

**Comment by baburdick** [comment]
I'm on v0.7.0. I don't see this issue.
