### ISSUE TITLE
Dependency on recent version of netrc gem

### ISSUE THREAD

**Issue by dominicsayers** [gemfury/gemfury#24]
This project depends on a quite recent version of the `netrc` gem

`s.add_dependency    "netrc", "~> 0.10.0"`

There are other gems that I would like to use (in particular `rest-client`) that depend on earlier versions of `netrc`. Is there any reason why earlier versions are not permitted?

**Comment by rykov** [comment]
@dominicsayers Which version of `rest-client` are you using?

**Comment by dominicsayers** [comment]
Apologies for not replying sooner. This issue appears to have gone away. I'm using `rest-client` 2.0.1 and `gemfury` 0.6.0.
