### ISSUE TITLE
fury git:list results in error message

### ISSUE THREAD

**Issue by twhiston** [gemfury/gemfury#26]
Running `fury git:list` in 0.6.0 results in the message "Oops! Something went wrong. Please contact support."
Using OSX 10.11.5 and ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]

**Comment by rykov** [comment]
@twhiston Can you please run the command with `DEBUG=true` and include the output:

    $ DEBUG=true fury git:list

**Comment by twhiston** [comment]
it seems to work now anyway, so maybe it was do with our account rather than the tool, as in the time since i made this we upgraded to a paid plan

**Comment by baburdick** [comment]
Works for me, too. This issue can probably be closed.

**Comment by rykov** [comment]
@twhiston @baburdick Thanks for following up. Closing.
