### ISSUE TITLE
Upload public package

### ISSUE THREAD

**Issue by hongquan** [gemfury/gemfury#31]
I'm using Gemfury to host some open source packages which I pre-build for ARM (because the official distribution only provides x86). Because they are open-source, I want to make all packages in my repository "public".

But until now, it takes much effort to "public" each of uploaded packages. Do you have any method to do it faster?

**Comment by rykov** [comment]
@hongquan Thanks for the suggestion.  We will add this to our backlog.

**Comment by hongquan** [comment]
Please also provide an area for public README (per repository). I want to write down instruction for how to install my public repository (how to configure `pip`, how to configure `apt`).

**Comment by rykov** [comment]
@hongquan We've added public package support to the CLI (v0.9.0+). You can now do `fury push --public` to upload public packages. We also support this option via cURL with `curl -F public=true`.

Thank you for the suggestion.
