### ISSUE TITLE
GemFury PyPI server embeds credentials in JSON responses

### ISSUE THREAD

**Issue by connorbrinton** [gemfury/gemfury#45]
Hi GemFury Team!

We use GemFury as a private PyPI repository, but have been suffering from compatibility issues with our chosen Python package management system, [Poetry](https://github.com/sdispater/poetry).

The main issue we're currently facing is that Poetry cannot handle the URLs which include embedded credentials as returned by the GemFury server. For example, listing all of our packages we get a response like (with ${FURY_TOKEN} replaced by our actual token):
```
<!DOCTYPE html>
<html>
  <head><title>Simple Index</title></head>
  <body>
    <a href="https://${FURY_TOKEN}:@pypi.fury.io/repo/package_one">package_one</a>
    ...
    <a href="https://${FURY_TOKEN}:@pypi.fury.io/repo/package_n">package_n</a>
  </body>
</html>
```

Because of [Poetry issue #746](https://github.com/sdispater/poetry/issues/746), Poetry fails to provide proper credentials when trying to follow requests including embedded credentials. We are currently working around this issue by using an in-house fork of Poetry.

However, beyond the inconvenience this causes, it's also a security issue for us, even when just using `pip`. As a result of the embedded credentials, we now have our GemFury token all over our dev, CI and prod logs, because it's printed every time `pip` installs something from our GemFury repository:
```
Collecting package_one==0.0.1 (from -r requirements.txt (line 38))
  Downloading https://${GEMFURY_TOKEN}:@pypi.fury.io/repo/-/ver_47e83/package_one-0.0.1.tar.gz
```

I know this is more of a server issue, so please let me know if I should direct this request to another channel.

Thanks!

**Comment by rykov** [comment]
@connorbrinton We've removed basic auth credentials from links in our PyPI repositories. Thank you for reporting this.
