### ISSUE TITLE
Publish failed PUT 503

### ISSUE THREAD

**Issue by iarroyo5** [gemfury/gemfury#48]
Gemfury throws `503` error when trying to publish a private `npm` package.

We hadn't had any issue publishing previous versions of our packages. We are using Docker with our build process, tests and linting working correctly. 

- Command: `npm publish`
- Node version: `lts/carbon`

```
npm ERR! publish Failed PUT 503
npm ERR! Unexpected token < in JSON at position 0
npm ERR! <!DOCTYPE html>
npm ERR!     <html>
npm ERR!       <head>
npm ERR!         <meta name="viewport" content="width=device-width, initial-scale=1">
npm ERR!         <meta charset="utf-8">
npm ERR!         <title>Application Error</title>
npm ERR!         <style media="screen">
npm ERR!           html,body,iframe {
npm ERR!             margin: 0;
npm ERR!             padding: 0;
npm ERR!           }
npm ERR!           html,body {
npm ERR!             height: 100%;
npm ERR!             overflow: hidden;
npm ERR!           }
npm ERR!           iframe {
npm ERR!             width: 100%;
npm ERR!             height: 100%;
npm ERR!             border: 0;
npm ERR!           }
npm ERR!         </style>
npm ERR!       </head>
npm ERR!       <body>
npm ERR!         <iframe src="//s3.amazonaws.com/fury-info/heroku/error.html"></iframe>
npm ERR!       </body>
npm ERR! </html>
```

**Comment by rykov** [comment]
Thank you for reporting this. It was a transient issue that has since been resolved.

From https://status.gemfury.com:
> One of our DNS records was pointing to a legacy load balancer which did not have the new configuration, and was returning 503 errors. We've updated the DNS records, and fixed the configuration.

**Comment by Chetan-unbounce** [comment]
@rykov for strange reasons I am getting "bad response Service Unavailable 503" for installing any of our packages hosted on Gemfury. They were all fine and suddenly started throwing error.

**Comment by dzleidig** [comment]
Seeing the same thing here...

**Comment by wpniederer** [comment]
I'm seeing this issue on a private repo well, it's blocking deployments. Their status page isn't updated, can we get some sort of response on this problem?

https://status.fury.co/

**Comment by bigwoof91** [comment]
Ditto what's been said above - my team is having the same issue and we can't install, publish... or even use `npm-proxy` to install public-npm packages. This is a major blocker for us...

Can we have some sort of update on this?

**Comment by prasvin** [comment]
Same here. Unable to fetch the gems. https://gem.fury.io says bad response Service Unavailable 503
I was expecting the status page https://status.fury.co/ to list some incident. Apparently, it's all green there.
