### ISSUE TITLE
Gemfury PHP repository returns URL's containing credentials

### ISSUE THREAD

**Issue by aboks** [gemfury/gemfury#51]
Similar to #45 (issue for PyPI), also the PHP Composer repository returns dist-URL's containing credentials. These eventually end up in the `composer.lock` file, causing the credentials of individual developers to be leaked to the entire team working on that project.

Is this something that could be fixed?

**Comment by markjeee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Investigate:](https://trello.com/c/BtSbiHdm/38-investigate)

**Comment by kenske** [comment]
I mentioned this same issue in August 2018 and never got a response:

https://twitter.com/kskertchly/status/1035631497867395073

**Comment by mwijngaard** [comment]
@markjeee This is quite a serious security flaw. I would expect this to receive a little more priority.

**Comment by mwijngaard** [comment]
I'm getting url's without credentials now, so it looks like this is fixed?

**Comment by rykov** [comment]
@mwijngaard Yes, this issue has been fixed. 🎉
