### ISSUE TITLE
Gemfury PHP repository does not process 'conflict'-constraints

### ISSUE THREAD

**Issue by aboks** [gemfury/gemfury#56]
If a PHP Composer package uploaded to Gemfury contains a `conflict`-constraint with another package (https://getcomposer.org/doc/04-schema.md#conflict), that constraint is not put into the `packages.json` index file that Gemfury offers to the composer CLI client. As a result, composer does not take the `conflict`-constraint into account when determining the set of packages to install, causing incompatible packages to show up together in a project.

To reproduce:

* Create a composer test project and install (say) `symfony/console` version `^3.4` in it.
* Create another package (say `foo/bar`), put `"conflict": { "symfony/console": "<4.0" }` in its `composer.json`, and upload it to Gemfury as version `1.0.0`.
* Try to install that version into the composer test project by running `composer require foo/bar=^1.0.0`

Expected result: Composer indicates that the requirements could not be resolved to an installable set of packages. The `packages.json` that composer retrieved from Gemfury and cached on disk contains the `conflict`-constraint.

Actual result: Composer installs `foo/bar` without complaining. The `packages.json` cached on disk lacks the `conflict`-constraint.

**Comment by rykov** [comment]
@aboks We've fixed this now. Thank you for the report. You may need to trigger a rebuild of your `packages.json`. This can be done by uploading a new package version, or by contacting support to have us trigger a rebuild manually.
