### ISSUE TITLE
CLI and API 'add collaborators' call does not work

### ISSUE THREAD

**Issue by ian-axelrod** [gemfury/gemfury#63]
Hi,

I want to use your API to programmatically add a collaborator to my gemfury project. Removing a collaborator works fine, but adding one does not. I get these messages in the CLI and programmatically, respectively.

```
Ian-Axelrod:ops-tools ianaxelrod$ fury sharing:add <MY EMAIL>
Oops! Something went wrong. Please contact support.
```

```
PUT /collaborators/<MY EMAIL>
...
404 Client Error: Not Found for url: https://api.fury.io/collaborators/<my email>
```

Any ideas? Cheers,

-Ian

**Comment by ian-axelrod** [comment]
Herro?

**Comment by markjeee** [comment]
@ian-axelrod Hi, i am able to re-produce the error. Let me investigate further.

**Comment by markjeee** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug in API for adding collaborators](https://trello.com/c/NUzkVcx2/91-bug-in-api-for-adding-collaborators)

**Comment by ian-axelrod** [comment]
Thank you.

**Comment by markjeee** [comment]
Hi @ian-axelrod, i realized, it only supports specifying the user by the username.

I tested both the API, using Curl and Gemfury CLI, and specified a username, and it works as expected. However, if i use the email address, it will return a 404.

Will this approach work for your use case?

**Comment by markjeee** [comment]
Realized, the CLI help text is not consistent, since it specified the parameter as email. Let me confirm with Gemfury team if both username and email is expected to be supported.

**Comment by rykov** [comment]
Hello @ian-axelrod @markjeee,

I've experimented with a few things, and the functionality is there, but with a few gotchas:

1. Be sure to specify that you're hitting API v1. You can do that either by prefixing the path with `/1` or having the User-Agent `application/vnd.fury.v1`

2. We use Rails, and it automatically uses the suffix of the URL path as the format.  So if you're hitting the URL `/1/collaborators/test%40example.com`, we see "test@example" as the username/email and "com" as the request format.   
It's quite annoying, actually, and we will look into whether this is something that should be turned off. In the meantime, you can bypass this by URL-encoding the periods in your email path component. So the URL would be `/1/collaborators/test%40example%2Ecom`.

Please give this a shot, and let us know if this works.

**Comment by rykov** [comment]
@ian-axelrod Have you had a chance to confirm that this solution works? I'll close this issue, but feel free to reopen if the API is still giving you trouble.
