### ISSUE TITLE
Publish gem via CI server (no `fury login`)

### ISSUE THREAD

**Issue by jesperronn** [gemfury/gemfury#66]
In a current project, I would like our CI server to publish new versions of a private gem. (This will trigger on tag creation in github).

Since I cannot ask the CI server to run `fury login`, is there an ENVIRONMENT_VARIABLE I can set with a pre-supplied token?

**Comment by rykov** [comment]
@jesperr Yes, it's possible using the `--api_token` option flag like so:

```
$ fury push gemfury-0.11.0.gem --as ACCOUNT --api_token PUSHTOKEN
```
