### ISSUE TITLE
Expired SSL certificate for fury.io

### ISSUE THREAD

**Issue by nicohvi** [gemfury/gemfury#81]
It seems the certificate for fury.io expired at 14:00 UTC +2 today:

![bilde](https://user-images.githubusercontent.com/430875/116875049-91318180-ac1a-11eb-8cf7-71ecf9e1ea39.png)

This precludes us from building our applications since we receive an SSL verification error from Bundler:

`Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://gem.fury.io/`

**Comment by mbelang** [comment]
Same here. I hope it will not take 1 day to solve this time.

**Comment by dezitter** [comment]
Seeing the same issue when installing dependencies from https://pypi.fury.io/:

```
Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091))
```

**Comment by laimonassutkus** [comment]
God damn it Fury, what the hell.

**Comment by dezitter** [comment]
https://status.fury.co/incidents/s0r0c1mkzv24
