### ISSUE TITLE
Upload error

### ISSUE THREAD

**Issue by rauldipeas** [gemfury/gemfury#86]
I'm getting this message when try to upload a package builded by myself.
![image](https://user-images.githubusercontent.com/12108031/171974960-1e2ba5ed-ce71-487e-a7ec-3c790efb63aa.png)

There's no log to debug.
![image](https://user-images.githubusercontent.com/12108031/171975328-65c111fa-c4c3-4d22-a8ef-c6e84db5711f.png)

This is the build script of package.
https://git.disroot.org/rauldipeas/apt-repository/src/branch/main/scripts/mkpkg/raindrop.sh

**Comment by rykov** [comment]
Thanks @rauldipeas for the bug report. We will take a look at why this file fails to be recognized.

**Comment by rauldipeas** [comment]
In fact, there are two packages failing to be recognized.
https://git.disroot.org/rauldipeas/apt-repository/src/branch/main/scripts/mkpkg/syncthingtray.sh

**Comment by rauldipeas** [comment]
Solved! Thank You so much!
![Screenshot_20220608_142120](https://user-images.githubusercontent.com/12108031/172679400-ff4f9437-4ee2-46e7-9608-a03213a13d8a.png)
