### ISSUE TITLE
Upgrade to Faraday 2.0

### ISSUE THREAD

**Issue by pboling** [gemfury/gemfury#90]
I'm removing dependencies on this gem (and updating workflows) until it is no longer blocking the Faraday 2.0 upgrade, so I'm creating this issue to track, as once it is complete I will add back.

**Comment by pboling** [comment]
On second thought it now seems like the best approach will be to cancel Gemfury.

**Comment by rykov** [comment]
@pboling We've released a new version [0.13.0.beta1](https://rubygems.org/gems/gemfury/versions/0.13.0.beta1) with upgraded dependencies.

**Comment by pboling** [comment]
@rykov Thanks!  Unfortunately that pre-release gem is not installable, it can't be seen by bundler at all, even though it is listed on rubygems.  Very strange bug.
See: https://github.com/rubygems/rubygems/issues/6982

Will there be a normal release of 0.13?
